name: Create Env File With Secrets

on:
  push:
    branches:
      - main

jobs:
  find-and-replace-database-url:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Find and Replace Database URL
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          files: .env
          find: "DATABASE_URL=.*"
          replace: "DATABASE_URL=${{ secrets.DATABASE_URL }}"