name: Create Env File With Secrets

on:
  push:
    branches:
      - main

jobs:
  find-and-replace-database-url:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set env database url
        run: |
          sed -i.bak "s|^DATABASE_URL=.*$|DATABASE_URL=${{ secrets.DATABASE_URL }}|g" .env
      - name: test
        run: |
          cat .env