name: Create Env File With Secrets

on:
  push:
    branches:
      - main

jobs:
  find-and-replace-database-url:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - shell: bash
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          echo "Replacing DATABASE_URL with secret"
          sed -i.bak 's|^DATABASE_URL=.*|DATABASE_URL=$DATABASE_URL|' .env && rm .env.bak
